import type { Localizer } from "./types";

export const DEFAULT_LOCALIZATION: Localizer = {
  primeTitle: (site) => `Sign in to ${site}`,
  primeSubtitle: (site) => `Enter your ${site} credentials to continue`,
  primeContinueButton: "Continue",
  primeLoadingButton: "Loading...",
  securityEncryption: "Your credentials are encrypted end-to-end",
  securityNoThirdParty: "Never shared with any third party",
  legalPrefix: "By continuing you agree to Kernel's",
  legalPrivacyPolicy: "Privacy Policy",
  legalTermsOfService: "Terms of Service",
  legalConjunction: "and",
  discoveringMessage: "Discovering login requirements...",
  waitingForFormMessage: "Waiting for login form...",
  submittingMessage: "Logging in...",
  loadingDiscoverySteps: [
    "Navigating to login page...",
    "Analyzing form structure...",
    "Identifying required fields...",
  ],
  loadingAuthSteps: [
    "Entering credentials...",
    "Submitting login form...",
    "Verifying authentication...",
  ],
  loadingTimeHint: "This may take 15-30 seconds...",
  loginTitle: (site) => `Log in to ${site}`,
  ssoLoginTitle: (provider) => `Log in with ${provider}`,
  ssoLoginSubtitle: (site) => `for ${site}`,
  mfaSelectTitle: "Choose verification method",
  mfaSelectSubtitle: "Select how you'd like to receive your verification code",
  signInSelectTitle: "Choose an option",
  signInSelectSubtitle: "Select which option to continue with",
  submitButton: "Continue",
  submittingButton: "Logging in...",
  ssoButtonLabel: (provider) => `Sign in with ${provider}`,
  orDivider: "or",
  passwordShow: "Show password",
  passwordHide: "Hide password",
  credentialSafetyNotice:
    "Your credentials are encrypted and sent directly from your browser. They are never shared with anyone or any LLM.",
  mfaTypeLabels: {
    sms: "Text message",
    call: "Phone call",
    email: "Email",
    totp: "Authenticator app",
    push: "Push notification",
    password: "Password",
    passkey: "Passkey",
    switch: "Use another method",
    other: "Other",
  },
  successTitle: "Successfully signed in",
  successDescription: (site) => `Your ${site} account is now connected`,
  successCloseHint: "You can now close this window",
  errorTitle: "Login failed",
  errorGenericMessage:
    "We encountered an unexpected issue while trying to log you in.",
  errorCodeLabel: "Error code",
  errorShowDetails: "Show details",
  errorHideDetails: "Hide details",
  errorCloseHint: "You can now close this window",
  expiredTitle: "Session Expired",
  expiredDescription:
    "This authentication session has expired. Please start a new session.",
  externalActionTitle: "Action Required",
  externalActionFallbackMessage: "Complete the verification on your device",
  externalActionWaiting: "Waiting for your confirmation...",
};
