import type { Localizer } from "./types";

export const DEFAULT_LOCALIZATION: Localizer = {
  primeTitle: (site) => `Sign in to ${site}`,
  primeSubtitle: (site) => `Enter your ${site} credentials to continue`,
  primeContinueButton: "Continue",
  primeLoadingButton: "Loading...",
  securityEncryption: "Your credentials are encrypted end-to-end",
  securityNoThirdParty: "Never shared with any third party",
  legalPrefix: "By continuing you agree to Kernel's",
  legalPrivacyPolicy: "Privacy Policy",
  legalTermsOfService: "Terms of Service",
  legalConjunction: "and",
  discoveringMessage: "Discovering login requirements...",
  waitingForFormMessage: "Waiting for login form...",
  submittingMessage: "Logging in...",
  loginTitle: (site) => `Log in to ${site}`,
  ssoLoginTitle: (provider) => `Log in with ${provider}`,
  ssoLoginSubtitle: (site) => `for ${site}`,
  mfaSelectTitle: "Choose verification method",
  mfaSelectSubtitle: "Select how you'd like to receive your verification code",
  signInSelectTitle: "Choose an option",
  signInSelectSubtitle: "Select which option to continue with",
  submitButton: "Continue",
  submittingButton: "Logging in...",
  ssoButtonLabel: (provider) => `Sign in with ${provider}`,
  orDivider: "or",
  passwordShow: "Show password",
  passwordHide: "Hide password",
  credentialSafetyNotice:
    "Your credentials are encrypted and sent directly from your browser. They are never shared with anyone or any LLM.",
  mfaTypeLabels: {
    sms: "Text message",
    call: "Phone call",
    email: "Email",
    totp: "Authenticator app",
    push: "Push notification",
    password: "Password",
    passkey: "Passkey",
    other: "Other",
  },
  successTitle: "You're signed in",
  successDescription: (site) => `Your session with ${site} is ready.`,
  errorTitle: "Something went wrong",
  errorGenericMessage: "We couldn't complete your login. Please try again.",
  errorCodeLabel: "Error code",
  expiredTitle: "Session Expired",
  expiredDescription:
    "This authentication session has expired. Please start a new session.",
  externalActionFallbackMessage: "Complete the verification on your device",
};
